# Generated by Django 4.1.2 on 2023-05-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название книги')),
                ('author', models.CharField(max_length=150, verbose_name='Автор книги')),
                ('translator', models.CharField(max_length=250, verbose_name='Переводчик')),
                ('publishing', models.CharField(max_length=250, verbose_name='Издательство')),
                ('series', models.CharField(max_length=250, verbose_name='Серия')),
                ('genre', models.CharField(max_length=150, verbose_name='Жанр книги')),
                ('years', models.CharField(max_length=150, verbose_name='Возрастное ограничение')),
                ('rating', models.CharField(max_length=50, verbose_name='Популярность книги')),
                ('comment', models.TextField(verbose_name='Описание книги')),
                ('price', models.CharField(max_length=50, verbose_name='Стоимость')),
                ('pages', models.CharField(max_length=250, verbose_name='Страницы')),
                ('weight', models.CharField(max_length=250, verbose_name='Масса')),
                ('dimensions', models.CharField(max_length=250, verbose_name='Размеры')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
